config/routes.rb
Rails.application.routes.draw do
  get 'events/index'

  get 'groups/index'

  root 'home#index'

  devise_for :users

  get 'home/index'

  resources :posts do
    resources :comments, only: [:index, :new, :create] do
      member { post :vote }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  lname                  :string
#  fname                  :string
#  phone                  :string
#  skype                  :string
#  site                   :string
#  description            :string
#  image                  :string
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/index.html.slim
h1 Events#index

app/views/groups/index.html.slim
h1 Groups#index

app/views/home/index.html.slim
div id="carousel-example-generic" class="carousel slide"
  ol class="carousel-indicators hidden-xs"
    li data-target="#carousel-example-generic" data-slide-to="0" class="active"
    li data-target="#carousel-example-generic" data-slide-to="1"
    li data-target="#carousel-example-generic" data-slide-to="2"

  div class="carousel-inner"
    div class="item active"
      img src="#{image_path("logo.png")}" alt=""
    div class="item"
      img src="#{image_path("logo.png")}" alt=""
    div class="item"
      img src="#{image_path("logo.png")}" alt=""


  a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"
    span class="icon-prev"
  a class="right carousel-control" href="#carousel-example-generic" data-slide="next"
    span class="icon-next"

h1 Home#index

app/views/layouts/application.html.slim
doctype html
html
  head
    title Blog
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags

  body
    nav.navbar.navbar-default
      .collapse.navbar-collapse id="bs-example-navbar-collapse-1"
        ul.nav.navbar-nav
          li = link_to 'Home', root_url
        ul.nav.navbar-nav
          li = link_to 'Events', events_index_path
        ul.nav.navbar-nav
          li = link_to 'Groups', groups_index_path
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            li
              br Signed in as #{current_user.email}

            li  = link_to 'Log out', destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out"
          - else
            li = link_to ' Sign up', new_user_registration_url, class: "glyphicon glyphicon-user"
            li = link_to ' Login', new_user_session_url, class: "glyphicon glyphicon-log-in"

    - if alert
      .alert.alert-danger
        = alert

    - if notice
      .alert.alert-info
        = notice
    img class="img-responsive img-full" src="#{image_path("logo.png")}" alt=""
    .container
      = yield